# Generated by Django 2.1.2 on 2018-12-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
